# Generated by Django 5.1 on 2026-02-22 19:28

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=web_app.models.category_image_upload_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cell',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
